### ISSUE TITLE
Remove MIT license header from source files

### ISSUE THREAD

**Issue by dvdsgl** [xamarin/app-crm#108]
We can license this app with a single license file at the root of the repo. I just watched a recorded demo and the big MIT comment block at the beginning of each file was a distraction, and also made Xamarin look 'open sourcey'.

**Comment by jsauvexamarin** [comment]
I was instructed by motz to do this. I can remove is necessary. Either that or you can set your IDE to collapse those comment blocks for demos.

**Comment by dvdsgl** [comment]
I spoke with Miguel about it and he agrees we should remove it for cleaner samples.
