### ISSUE TITLE
Cannot Compile on VS2013 Due To Null-Conditional Operator

### ISSUE THREAD

**Issue by jimmgarrido** [xamarin/app-crm#92]
Line 105 in CustomersViewModel.cs uses a null-conditional operator `Address = address?.ToString()` which prevents users on VS 2013 from compiling the project successfully without modifying the code.

This leads to a bad first run experience and possibly deters VS2013 users who might not necessarily know this is a new feature in C# 6.0.

**Comment by pauldendulk** [comment]
Yeah silly. I have Xamarin Studio and VS2013 and cannot run the sample without modifications. I had to remove ?. twice and add e ..' = new Font()' in SalesDashboardChartview.ChartAxisFont. After that no problems.

**Comment by jsauvexamarin** [comment]
The README is clear that VS2015 is required, due to C# 6 features.
